"""Curated public security sources used to seed the red-line knowledge base.

The records contain original summaries and platform-oriented guidance, not
copies of third-party documents. ``source_url`` always points reviewers back
to the public source for the authoritative wording.
"""

OFFICIAL_KNOWLEDGE_SOURCES = [
    {
        "source_id": "tc260-generative-ai-basic-security-2024",
        "title": "TC260-003 生成式人工智能服务安全基本要求",
        "publisher": "全国网络安全标准化技术委员会",
        "category": "国家法规",
        "document_type": "technical_standard",
        "updated_at": "2024-02-29",
        "source_url": "https://www.tc260.org.cn/portal/article/2/20240301164054",
        "local_filename": "upload_2024-03-01_1709282398070082466.pdf",
        "summary": "覆盖语料来源、内容和标注安全，模型安全、安全措施、测试题库及评估方法。",
        "content": """本技术文件适用于生成式人工智能服务提供者开展安全评估和提高安全水平。文件提出训练语料来源可追溯、违法不良信息过滤、知识产权和个人信息保护要求；安全性标注应覆盖主要风险并经审核人员复核。模型侧要求对用户输入开展安全性检测，常态化监测生成内容，并通过针对性优化处置问题。安全措施包括适用人群和场景、透明度、用户输入用于训练的关闭机制、生成内容标识、关键词库、生成内容测试题库、拒答测试题库和分类模型。平台应用：可用于完善红线分类、测试集管理、人工试标规则和大模型护栏评测。""",
    },
    {
        "source_id": "gbt-45654-2025",
        "title": "GB/T 45654-2025 生成式人工智能服务安全基本要求",
        "publisher": "国家市场监督管理总局、国家标准化管理委员会",
        "category": "国家法规",
        "document_type": "national_standard",
        "updated_at": "2025-04-25",
        "source_url": "https://www.tc260.org.cn/portal/article/1/20250630122232",
        "local_filename": "upload_2025-06-30_1751257342816036759.pdf",
        "summary": "生成式人工智能训练数据、模型、安全措施与安全评估的国家标准，2025 年 11 月实施。",
        "content": """GB/T 45654-2025 规定生成式人工智能服务在训练数据安全、模型安全和安全措施方面的要求，并给出主要安全风险和安全评估参考方法。训练数据要求包括来源选择、多样性、来源管理与追溯、内容过滤、知识产权、个人信息和数据标注安全。模型要求覆盖生成内容安全、准确性与可靠性。平台应用：把附录风险分类映射为红线知识库标签，把评估方法用于护栏测试集、拒答测试、生成内容安全抽检和比赛测试报告。标准条文的最终解释以正式文本为准。""",
    },
    {
        "source_id": "samr-gbt-45654-record",
        "title": "GB/T 45654-2025 国家标准公开记录",
        "publisher": "国家标准全文公开系统",
        "category": "国家法规",
        "document_type": "standard_record",
        "updated_at": "2025-04-25",
        "source_url": "https://std.samr.gov.cn/gb/search/gbDetailed?id=33D40F1160BF5D92E06397BE0A0A5B93",
        "summary": "国家标准编号、发布日期、实施日期与标准状态的权威查询入口。",
        "content": """本条目用于核验 GB/T 45654-2025《网络安全技术 生成式人工智能服务安全基本要求》的标准编号、发布日期、实施日期和现行状态。知识库把标准正文与标准元数据分开保存：正文用于检索具体要求，公开系统记录用于核验标准身份与状态。审核员引用标准时应同时写明标准编号和版本，避免将 2024 年 TC260 技术文件与 2025 年国家标准混为同一版本。""",
    },
    {
        "source_id": "nsfocus-aiss-ai-security",
        "title": "绿盟 AISS 人工智能安全解决方案参考",
        "publisher": "绿盟科技",
        "category": "内容安全",
        "document_type": "vendor_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://aiss.nsfocus.com/",
        "summary": "面向大模型与生成式人工智能的安全治理、风险检测和评测能力参考。",
        "content": """绿盟 AISS 公共站点可作为人工智能安全产品能力对齐参考。平台调研时重点比较大模型输入输出内容安全、提示注入与越狱风险、敏感信息泄露、模型和应用风险评测、知识库与插件调用安全以及安全运营闭环。厂商公开页面用于产品能力研究，不作为本平台检测结论的直接证据；具体能力、适用范围与服务边界以绿盟官方说明为准。平台可借鉴统一风险分类、检测证据、处置建议和评测报告结构，并保留本地模型与第三方能力的来源标记。""",
    },
    {
        "source_id": "cn-genai-interim-measures-2023",
        "title": "生成式人工智能服务管理暂行办法",
        "publisher": "国家互联网信息办公室等七部门",
        "category": "国家法规",
        "document_type": "regulation",
        "updated_at": "2023-07-13",
        "source_url": "https://www.gov.cn/zhengce/zhengceku/202307/content_6891752.htm",
        "summary": "生成式人工智能服务的内容治理、数据处理、标识与投诉处置基线。",
        "content": """适用范围：向中华人民共和国境内公众提供生成文本、图片、音频、视频等内容的生成式人工智能服务。治理要求：坚持发展和安全并重，提供者应依法承担网络信息内容生产者责任，采取有效措施防范违法和不良信息；发现违法内容应及时停止生成、停止传输、消除并采取模型优化训练等整改措施。数据与个人信息：训练数据处理应有合法来源，不得侵害知识产权；涉及个人信息时应取得同意或符合法定情形。服务治理：应提高透明度和生成内容准确性、可靠性，建立投诉举报机制。平台应用：本系统可将其转化为内容安全规则、人工复核升级条件、日志留存和处置闭环，但检索命中本材料不等于已判定违法。""",
    },
    {
        "source_id": "cn-ai-content-labeling-2025",
        "title": "人工智能生成合成内容标识办法",
        "publisher": "国家互联网信息办公室等四部门",
        "category": "国家法规",
        "document_type": "regulation",
        "updated_at": "2025-03-14",
        "source_url": "https://www.cac.gov.cn/2025-03/14/c_1743654684782215.htm",
        "summary": "规定文本、图片、音频、视频和虚拟场景的显式、隐式标识责任。",
        "content": """核心要求：人工智能生成合成内容标识分为显式标识和隐式标识。显式标识应让用户能够明显感知；隐式标识通过技术措施写入文件数据。服务提供者、内容传播服务提供者、应用分发平台和用户分别承担相应责任。对图片场景，平台审核应分别记录可见标识、文件元数据或隐式标识线索以及来源取证结果。标识缺失不能直接推出内容不是 AI 生成，存在标识也不能替代内容安全审核。平台应用：来源证据区应并列展示 C2PA、IPTC/EXIF、隐式水印和模型检测结果，保留证据边界。""",
    },
    {
        "source_id": "cn-network-data-regulation-2024",
        "title": "网络数据安全管理条例",
        "publisher": "国务院",
        "category": "国家法规",
        "document_type": "regulation",
        "updated_at": "2024-09-30",
        "source_url": "https://www.gov.cn/zhengce/content/202409/content_6977766.htm",
        "summary": "网络数据处理、个人信息保护、重要数据与平台义务的综合治理要求。",
        "content": """网络数据处理者应建立健全网络数据安全管理制度，采取加密、备份、访问控制、安全认证等技术措施，并处置安全事件。个人信息处理应遵循合法、正当、必要和诚信原则，公开处理规则并保障个人权利。平台应用：审核系统保存原始提示词、危险输出、图片证据和 IP 线索时，应执行最小必要、访问控制、审计记录、保留期限和脱敏展示；第三方检测上传必须单独告知并取得明确确认。""",
    },
    {
        "source_id": "cn-deep-synthesis-governance",
        "title": "互联网信息服务深度合成管理规定",
        "publisher": "国家互联网信息办公室等三部门",
        "category": "国家法规",
        "document_type": "regulation",
        "updated_at": "2022-11-25",
        "source_url": "https://www.cac.gov.cn/2022-12/11/c_1672221949354811.htm",
        "summary": "深度合成服务的数据、内容、标识、安全评估与投诉治理规则。",
        "content": """深度合成服务提供者应落实信息安全主体责任，建立用户注册、算法机制机理审核、科技伦理审查、信息发布审核、数据安全和个人信息保护、反电信网络诈骗、应急处置等制度。对可能导致公众混淆或者误认的深度合成内容，应在合理位置作出显著标识。平台应用：人脸替换、人物属性编辑、语音合成和虚拟场景等应作为重点审核对象；审核记录应包含原始输入、模型结果、标识线索和人工复核结论。""",
    },
    {
        "source_id": "content-safety-review-baseline",
        "title": "内容安全人工复核与证据保全基线",
        "publisher": "平台安全研究组",
        "category": "内容安全",
        "document_type": "curated_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://www.gov.cn/zhengce/zhengceku/202307/content_6891752.htm",
        "summary": "把模型风险信号转化为可解释、可复核、可追溯的审核流程。",
        "content": """审核对象分为内容本身、生成来源、传播语境和潜在影响四层。机器结果只能作为风险信号，审核员必须能看到原始文本或受控原图、命中规则、模型解释、来源证据和上下文。建议结论使用安全、存疑、危险三级：安全表示证据支持放行；存疑表示证据不足或需要上级复核；危险表示命中明确红线并应阻断。高风险案例应保留事件 ID、样本哈希、时间、模型版本、规则版本和人工意见。不得用检索相似度直接替代违规判定。""",
    },
    {
        "source_id": "content-safety-risk-taxonomy",
        "title": "图片与多模态内容风险分类参考",
        "publisher": "平台安全研究组",
        "category": "内容安全",
        "document_type": "curated_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://www.cac.gov.cn/2025-03/14/c_1743654684782215.htm",
        "summary": "覆盖敏感政治内容、成人内容、暴力、武器、诈骗、营销与未成年人风险。",
        "content": """建议一级分类包括：政治与国家安全、成人与性暗示、暴力血腥、武器与危险品、自伤自杀、未成年人安全、个人信息与隐私、诈骗钓鱼、违法营销、仇恨歧视、虚假事实和 AIGC 来源标识。审核时记录对象、行为、场景、严重度、置信度和证据区域。成人、血腥和敏感政治样本在列表中应默认打码，只有具有权限的审核员主动展开。涉及新闻、教育、医疗或艺术语境时不能只依据视觉关键词，需要结合用途和上下文复核。""",
    },
    {
        "source_id": "content-safety-pii-handling",
        "title": "个人信息与敏感证件审核指南",
        "publisher": "平台安全研究组",
        "category": "内容安全",
        "document_type": "curated_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://www.gov.cn/zhengce/content/202409/content_6977766.htm",
        "summary": "身份证件、人脸、联系方式和位置数据的最小化处理与脱敏要求。",
        "content": """身份证、驾驶证、银行卡、人脸生物特征、精确位置、手机号等属于需要重点保护的信息。审核界面应优先展示脱敏副本，原图访问应受权限控制并写入审计日志。样本不得进入公开截图、飞书文档或代码仓库；测试报告使用合成样本并明确标注。模型调用仅传输完成审核所必需的数据，外部供应商调用前必须告知上传目的、供应商和风险。""",
    },
    {
        "source_id": "tencent-cloud-image-moderation",
        "title": "腾讯云图片内容安全实践摘要",
        "publisher": "腾讯云",
        "category": "腾讯云安全",
        "document_type": "vendor_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://cloud.tencent.com/document/product/1125/37109",
        "summary": "图片审核服务的接入、策略配置、标签结果和业务闭环参考。",
        "content": """腾讯云图片内容安全公开文档展示了云端内容审核服务的典型形态：接入服务、配置策略、调用检测接口、读取标签与处置建议，并结合业务场景调整阈值和名单。可借鉴点：审核结果应输出明确标签、置信度或分值、建议动作和请求标识；同步接口需考虑超时、文件限制、失败重试和幂等；自定义规则与黑白名单应与通用模型分开管理。平台对齐：当前图片审核可保留本地模型结果，同时增加统一标签映射和人工复核入口。具体能力和参数以腾讯云原文为准。""",
    },
    {
        "source_id": "tencent-cloud-image-moderation-api",
        "title": "腾讯云图片同步检测接口设计参考",
        "publisher": "腾讯云",
        "category": "腾讯云安全",
        "document_type": "vendor_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://cloud.tencent.com/document/product/1125/53273",
        "summary": "同步审核 API 的输入限制、返回结构和异常处理参考。",
        "content": """同步内容审核接口适合单次审核与低延迟业务，但必须对文件类型、尺寸、请求超时、服务端错误和限流做明确处理。平台 API 应返回 request_id、状态、风险标签、分值、证据、延迟和模型版本；429、5xx、超时与未配置必须显示为不可判定或服务异常，不能误写为安全。调用日志不得保存密钥和未脱敏原图。""",
    },
    {
        "source_id": "360-netlab-threat-intelligence",
        "title": "360 Netlab 威胁情报研究使用指南",
        "publisher": "360 Netlab",
        "category": "360 安全",
        "document_type": "vendor_research",
        "updated_at": "2026-08-06",
        "source_url": "https://blog.netlab.360.com/",
        "summary": "将公开威胁研究中的 IOC、攻击行为和处置建议转化为可检索证据。",
        "content": """360 Netlab 持续发布僵尸网络、恶意基础设施、漏洞利用和网络攻击活动研究。知识库接入此类材料时，应记录标题、发布时间、研究机构、原始链接、IOC 类型、攻击阶段和适用范围；IOC 具有时效性，不应脱离报告上下文直接作为永久封禁依据。平台可将域名、IP、URL、文件哈希和行为描述作为安全扫描与审计的辅助证据，并标注首次发现、最近验证和置信状态。具体技术结论以原始报告为准。""",
    },
    {
        "source_id": "360-ti-operational-guidance",
        "title": "360 威胁情报中心运营参考",
        "publisher": "360 数字安全",
        "category": "360 安全",
        "document_type": "vendor_guide",
        "updated_at": "2026-08-06",
        "source_url": "https://ti.360.net/",
        "summary": "威胁情报查询、证据时效与告警关联的运营参考。",
        "content": """威胁情报用于补充 IP、域名、URL 和文件哈希的风险上下文。应用时需要区分观测事实、分析判断和处置建议，并记录数据时间、来源和置信度。一个来源 IP 命中历史威胁情报不等于当前请求恶意，应结合接口行为、调用频率、内容风险与人工调查。平台可在驾驶舱地图和审计日志中显示脱敏 IP 地理信息与风险标签，但不得虚构真实攻击归属。""",
    },
    {
        "source_id": "chaitin-safeline-overview",
        "title": "SafeLine 雷池 WAF 开源架构与防护实践",
        "publisher": "长亭科技",
        "category": "长亭安全",
        "document_type": "open_source",
        "updated_at": "2026-08-06",
        "source_url": "https://github.com/chaitin/SafeLine",
        "summary": "自托管 Web 应用防火墙的部署、防护、日志与事件分析参考。",
        "content": """SafeLine 是长亭科技公开的自托管 Web 应用防火墙项目，可作为平台 API 暴露后的边界防护参考。WAF 位于客户端与业务服务之间，对 HTTP 流量进行检测和处置。平台借鉴点包括：反向代理接入、攻击检测、访问控制、频率限制、事件日志和防护站点管理。WAF 不能替代应用鉴权、输入验证或大模型安全护栏；部署时应保留真实客户端 IP 的可信传递链，并防止客户端伪造转发头。具体许可、版本和部署要求以开源仓库为准。""",
    },
    {
        "source_id": "chaitin-safeline-incident-evidence",
        "title": "SafeLine 告警证据与事件处置参考",
        "publisher": "长亭科技",
        "category": "长亭安全",
        "document_type": "open_source",
        "updated_at": "2026-08-06",
        "source_url": "https://help.waf-ce.chaitin.cn/",
        "summary": "Web 攻击告警、攻击类型、请求证据和处置闭环参考。",
        "content": """WAF 告警需要让运营人员看懂请求时间、来源、目标站点、路径、攻击类型、处置动作和关键证据。面向本平台，API 日志可关联请求 ID、来源 IP、认证主体、接口、状态码、延迟和内容审核事件 ID；危险请求原文只在受控详情中展示。告警统计应以真实日志为主，演示数据必须标记为模拟，不能与生产事实混合。对 SQL 注入、XSS、路径穿越等 Web 攻击，应由 WAF 和应用安全链路处置，而不是交给内容审核模型判断。""",
    },
]
