<template><header class="cockpit-header"><div class="brand"><span class="brand-mark"><ShieldCheck :size="20" /></span><span><strong>AIGC 安全运营台</strong><small>AIGC SECURITY OPERATIONS</small></span></div><div class="title"><span class="wing"></span><h1>{{ title }}<small>{{ subtitle }}</small></h1><span class="wing reverse"></span></div><div class="clock"><strong>{{ clock }}</strong><small>{{ date }}</small><button title="退出大屏" aria-label="退出大屏" @click="$emit('exit')"><Minimize2 :size="16" /></button></div></header></template>
<script setup lang="ts">
import { Minimize2, ShieldCheck } from 'lucide-vue-next'
defineProps<{ title: string; subtitle: string; clock: string; date: string }>()
defineEmits<{ exit: [] }>()
</script>
<style scoped>
.cockpit-header{height:var(--screen-header-height);display:grid;grid-template-columns:1fr auto 1fr;align-items:center;border-bottom:1px solid var(--screen-line-soft)}.brand,.brand>span:last-child,.clock{display:flex;align-items:center}.brand{gap:10px}.brand>span:last-child{flex-direction:column;align-items:flex-start;gap:3px}.brand strong{color:var(--screen-text);font-size:var(--fs-screen-title);font-weight:600}.brand small,.title small,.clock small{color:var(--screen-text-faint);font:var(--fs-screen-code) var(--font-code);letter-spacing:.12em}.brand-mark{display:grid;place-items:center;width:36px;height:36px;color:var(--screen-blue);border:1px solid var(--screen-line);border-radius:var(--screen-radius-sm);box-shadow:var(--screen-glow)}.title{display:flex;align-items:center;gap:16px}.title h1{margin:0;color:var(--screen-text);font-size:var(--fs-screen-hero);font-weight:700;letter-spacing:.04em;text-align:center;text-shadow:0 0 26px rgba(42,201,255,.32);white-space:nowrap}.title h1 small{display:block;margin-top:4px;font-weight:400}.wing{width:92px;height:1px;background:linear-gradient(90deg,transparent,var(--screen-blue));box-shadow:0 0 8px var(--screen-blue)}.wing.reverse{transform:scaleX(-1)}.clock{justify-content:flex-end;gap:10px}.clock strong{color:var(--screen-text);font:600 22px var(--font-number);font-variant-numeric:tabular-nums}.clock small{align-self:flex-end;letter-spacing:0}.clock button{display:grid;place-items:center;width:34px;height:34px;color:var(--screen-text-muted);border:1px solid var(--screen-line);border-radius:var(--screen-radius-sm);background:var(--screen-surface-soft);cursor:pointer}.clock button:hover{color:var(--screen-text);border-color:var(--screen-line-focus)}
.brand-mark{color:#e9fbff;border-color:rgba(76,192,255,.52);background:linear-gradient(145deg,rgba(18,123,190,.88),rgba(5,48,104,.92));box-shadow:inset 0 1px rgba(224,250,255,.20),0 0 16px rgba(22,140,255,.24)}.brand-mark :deep(svg){stroke-width:2.1;filter:drop-shadow(0 0 5px rgba(218,248,255,.72))}
</style>
