<template>
  <section class="specialist-evidence" :class="{ 'perspective-evidence': isPerspective }" :aria-label="`${title}模型证据`">
    <div class="specialist-head"><div><span class="specialist-kicker">{{ kicker }}</span><h4>{{ title }}</h4></div><span class="specialist-status" :class="`status-${evidence.status}`">{{ statusLabel }}</span></div>
    <div class="specialist-metrics"><div><span>模型</span><b>{{ evidence.model || '未配置' }}</b></div><div><span>风险分数</span><b>{{ evidence.risk_score == null ? '不可用' : `${Math.round(evidence.risk_score * 100)}%` }}</b></div><div><span>耗时</span><b>{{ evidence.latency_ms ?? 0 }} ms</b></div></div>
    <div v-if="scoreEntries.length" class="score-list"><div v-for="item in scoreEntries" :key="item.code" class="score-row"><span>{{ labels[item.code] || item.code }}</span><strong>{{ Math.round(item.score * 100) }}%</strong><div class="score-track"><i :style="{ width: `${item.score * 100}%` }"></i></div></div></div>
    <p class="specialist-note"><template v-if="evidence.status === 'not_run'">主审核已发现风险，本次无需调用重模型二次复核。</template><template v-else-if="evidence.status === 'not_configured'">GPU 专家服务未配置；本项不参与最终处置。</template><template v-else-if="evidence.status === 'inconclusive'">专家服务未返回可判定结果，已保留为无法确认并交人工复核。</template><template v-else-if="isPerspective">PerspectiveVision 仅作为二次复核证据；发现风险时转人工复核，不直接自动阻断。</template><template v-else>UnsafeBench 作为主审核专家证据，与多模态解释结果并列展示。</template></p>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
const props = withDefaults(defineProps<{ evidence: Record<string, any>, variant?: 'unsafe-bench' | 'perspective' }>(), { variant: 'unsafe-bench' })
const labels: Record<string, string> = { sexual: '性内容', violence: '暴力', hateful: '仇恨', shocking: '冲击性内容', self_harm: '自伤', political: '政治', illegal_activity: '违法活动', deception: '欺骗', spam: '垃圾营销', harassment: '骚扰', health: '健康风险' }
const isPerspective = computed(() => props.variant === 'perspective')
const kicker = computed(() => isPerspective.value ? 'PERSPECTIVE SECONDARY' : 'UNSAFEBENCH PRIMARY')
const title = computed(() => isPerspective.value ? 'PerspectiveVision 二次复核' : 'UnsafeBench 主审核')
const statusLabel = computed(() => ({ detected: '发现风险', not_detected: '未发现风险', inconclusive: '无法确认', not_configured: '未启用', not_run: '已跳过' }[props.evidence.status] || '未知状态'))
const scoreEntries = computed(() => Object.entries(props.evidence.category_scores || {}).map(([code, score]) => ({ code, score: Math.max(0, Math.min(1, Number(score) || 0)) })).filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 8))
</script>
<style scoped>
.specialist-evidence{margin-top:16px;padding:16px;border:1px solid #d9e2ec;border-left:3px solid #7c3aed;background:#faf8ff;border-radius:6px}.perspective-evidence{border-left-color:#0f766e;background:#f4fbfa}.specialist-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.specialist-kicker{display:block;color:#6d28d9;font-size:11px;font-weight:700}.perspective-evidence .specialist-kicker{color:#0f766e}.specialist-head h4{margin:3px 0 0;color:#172033;font-size:15px;font-weight:650}.specialist-status{padding:4px 8px;border-radius:4px;background:#e2e8f0;color:#475569;font-size:12px;font-weight:650}.status-detected{background:#fee2e2;color:#b42318}.status-not_detected{background:#dcfce7;color:#166534}.status-inconclusive{background:#fef3c7;color:#92400e}.status-not_run{background:#e2e8f0;color:#475569}.specialist-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:14px}.specialist-metrics div{padding:9px 10px;border:1px solid #e5eaf0;background:#fff;border-radius:4px}.specialist-metrics span{display:block;color:#64748b;font-size:11px}.specialist-metrics b{display:block;margin-top:3px;color:#172033;font-size:14px}.score-list{margin-top:12px}.score-row{display:grid;grid-template-columns:100px 42px 1fr;align-items:center;gap:8px;margin-top:7px;color:#475569;font-size:12px}.score-row strong{text-align:right;color:#172033}.score-track{height:5px;background:#ede9fe;border-radius:3px;overflow:hidden}.score-track i{display:block;height:100%;background:#7c3aed;border-radius:3px}.specialist-note{margin:12px 0 0;color:#526071;font-size:12px;line-height:1.65}@media(max-width:640px){.specialist-metrics{grid-template-columns:1fr}.score-row{grid-template-columns:85px 40px 1fr}}
</style>
